[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
minjame = "HRTBy3VHDdcG797EH5m6z4zXm9j9VmuuSPnstNrHGC3B"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
